stages:          # List of stages for jobs, and their order of execution - ttt
  - build

build-dev:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - buildx
  script:
    - echo "Compiling the code..."
    - docker buildx build -t gitlab.hacknix.net:5050/hacknix/$CI_PROJECT_NAME:development-latest --platform linux/amd64,linux/i386 --push .



    - echo "Compile complete."
  only:
    - master

build-release:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - buildx
  script:
    - echo "Compiling the code..."
    - cd docker-configs
    - docker buildx build --no-cache -t gitlab.hacknix.net:5050/hacknix/$CI_PROJECT_NAME:latest -t gitlab.hacknix.net:5050/hacknix/$CI_PROJECT_NAME:$CI_COMMIT_TAG -t gitlab.hacknix.net:5050/hacknix/$CI_PROJECT_NAME:development-latest --platform linux/arm/v7,linux/amd64,linux/i386,linux/arm64  --push .



    - echo "Compile complete."
  only:
    - tags
