    D-APRS:
        container_name: D-APRS
        environment:
        #Enviroment variables
          - APRS_CALL=<YOUR CALL>
          - APRS_PASSCODE=<PASS>
          - MASTER_IP=<External IP / Domain of this master>
        image: 'shaymez/rysen:latest'
        #Container will persist over reboots
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.40
