    D-APRS:
        container_name: D-APRS
        environment:
          - APRS_CALL=<YOUR CALL>
          - APRS_PASSCODE=<PASS>
        volumes:
          - '/etc/rysen/aprs/gps_data.cfg:/opt/gps_data.cfg'
          - '/etc/rysen/aprs/usersettings.txt:/usersettings/usersettings.txt'
        image: 'shaymez/rysen:latest'
        #Container will persist over reboots
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.40
