    #Add this snippet to your docker-compose.yml
    D-APRS:
        container_name: D-APRS
        environment:
          - APRS_CALL=
          - APRS_PASSCODE=
        volumes:
          - usersettings:/opt/volume/:rw
        image: 'gitlab.hacknix.net:5050/hacknix/docker-freedmr-kf7eel-gps_data:development-latest'
        #Container will persist over reboots
        restart: "unless-stopped"

