   # Add this snippet into your docker-compose.yml file to include D-APRS into RYSEN / FreeDMR
   D-APRS:
        container_name: D-APRS
        volumes:
        #Read JSON files outside of container (Download JSON externally!)
          - '/etc/rysen/json/peer_ids.json:/opt/usersettings/peer_ids.json'
          - '/etc/rysen/json/subscriber_ids.json:/opt/usersettings/subscriber_ids.json'
          - '/etc/rysen/json/talkgroup_ids.json:/opt/usersettings/talkgroup_ids.json'
        environment:
        #Enviroment variables
          - APRS_CALL=<YOUR CALL INCLUDING YOUR SSID eg M1ABC-12>
          - APRS_SSID=<APRS SSID FOR YOUR SERVER eg 12>
          - APRS_PASSCODE=<PASSCODE GENERATED VIA MAGICBUG>
          - DATA_DMR_ID=<ENTER DMR TG / PRIVATE CALL NUMBER TO ROUTE APRS>
          - MASTER_IP=<EXT IP OF MASTER / DOMAIN NAME>
          - MASTER_PASS=<PASSWORD FOR MASTER>
        image: 'shaymez/rysen:latest'
        #Container will persist over reboots
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.40
