    D-APRS:
        container_name: D-APRS
        environment:
        #Enviroment variables
          - APRS_CALL=<YOUR CALL>
          - APRS_SSID=<APRS SSID FOR YOUR CALL>
          - APRS_PASSCODE=<PASS>
          - DMR_DATA_ID=<ENTER DMR TG / PRIVATE CALL NUMBER TO ROUTE APRS>
          - MASTER_IP=<EXT IP OF MASTER / DOMAIN NAME>
        image: 'shaymez/rysen:latest'
        #Container will persist over reboots
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.40
