#!/bin/ash
cd /opt

#Substitute enivronment variables into files
sed -i "s/{{APRS_CALL}}/$APRS_CALL/" /opt/gps_data.cfg
sed -i "s/{{APRS_SSID}}/$APRS_SSID/" /opt/gps_data.cfg
sed -i "s/{{APRS_PASSCODE}}/$APRS_PASSCODE/" /opt/gps_data.cfg
sed -i "s/{{DATA_DMR_ID}}/$DATA_DMR_ID/" /opt/gps_data.cfg
sed -i "s/{{MASTER_IP}}/$MASTER_IP/" /opt/gps_data.cfg
sed -i "s/{{MASTER_PASS}}/$MASTER_PASS/" /opt/gps_data.cfg


python /opt/hbnet/data_gateway.py -c /opt/gps_data.cfg
