#!/bin/sh
###############################################################################
# Copyright (C) 2020 Simon Adlem, G7RZU <g7rzu@gb7fr.org.uk>  
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
###############################################################################

cd /opt

#Substitute enivronment variables into files
sed -i "s/{{APRS_CALL}}/$APRS_CALL/" /opt/gps_data.cfg
sed -i "s/{{APRS_PASSCODE}}/$APRS_PASSCODE/" /opt/gps_data.cfg


python /opt/hbnet/gps_data.py -c /opt/gps_data.cfg
